name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v5
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main

  build:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
            extra-conf: |
              extra-experimental-features = nix-command flakes recursive-nix pipe-operators

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Show flake
        run: nix flake show

      - name: Check flake
        run: nix flake check
      # - name: Build
      #   run: |
      #     for host in $(nix eval .#hosts --accept-flake-config --json | jq -r '.[]'); do
      #       if [ "$host" = "installer" ]; then
      #         continue
      #       fi
      #       echo "Building for $host"
      #       nix build -L --accept-flake-config ".#nixosConfigurations.${host}.config.system.build.toplevel"
      #     done
      # - name: Deploy
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
      #   run: |
      #     cachix push domenkozar-private ./result
      #     cachix deploy activate --agent cherimoya ./result
