name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@786422608c7bded2bbc9741ad9f91356842bf520 # main

  build:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
        with:
            extra-conf: |
              extra-experimental-features = nix-command flakes recursive-nix pipe-operators

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15

      - name: Show flake
        run: nix flake show

      - name: Check flake
        run: nix flake check
      # - name: Build
      #   run: |
      #     for host in $(nix eval .#hosts --accept-flake-config --json | jq -r '.[]'); do
      #       if [ "$host" = "installer" ]; then
      #         continue
      #       fi
      #       echo "Building for $host"
      #       nix build -L --accept-flake-config ".#nixosConfigurations.${host}.config.system.build.toplevel"
      #     done
      # - name: Deploy
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
      #   run: |
      #     cachix push domenkozar-private ./result
      #     cachix deploy activate --agent cherimoya ./result
